{"dfa67803b85409dc4dc7238338c1a47d":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":0,"unknown":0,"total":6},"items":[{"uid":"1d99b990f7e826f3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/1d060df43f911874e774e595a91a2861/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88b4ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935605,"stop":1717321935609,"duration":4}},{"uid":"57db773b75b4c672","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/1d060df43f911874e774e595a91a2861/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88b4ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935605,"stop":1717321935609,"duration":4}},{"uid":"ee89cb334a09f860","reportUrl":"../2/index.html#testresult/ee89cb334a09f860","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/1d060df43f911874e774e595a91a2861/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88b4ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935605,"stop":1717321935609,"duration":4}},{"uid":"b58007e654e5f02d","reportUrl":"../1/index.html#testresult/b58007e654e5f02d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/1d060df43f911874e774e595a91a2861/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88b4ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935605,"stop":1717321935609,"duration":4}},{"uid":"57fb4b4f246d864","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/1d060df43f911874e774e595a91a2861/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88b4ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935605,"stop":1717321935609,"duration":4}},{"uid":"9bffc1adf918635c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/1d060df43f911874e774e595a91a2861/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88b4ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935605,"stop":1717321935609,"duration":4}}]},"274fb7bbdd30ec64eac3f9cfdc569a9b":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"5526cd3392ac2eb9","status":"passed","time":{"start":1716908343047,"stop":1716908348737,"duration":5690}}]},"a43b13a284001007b8eddfe8372100a1":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"d2ca85e352f4c303","status":"passed","time":{"start":1716978883787,"stop":1716978904605,"duration":20818}}]},"a19f6aca9cdea091ec68b1144e9c2c26":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":0,"unknown":0,"total":6},"items":[{"uid":"c8c48017b72bc3f1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/8445ede51857ce7b42f9ef7a26ce4c7d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc8886cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321936248,"stop":1717321936252,"duration":4}},{"uid":"2e5d3e61c6bb30bf","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/8445ede51857ce7b42f9ef7a26ce4c7d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc8886cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321936248,"stop":1717321936252,"duration":4}},{"uid":"391488c3c9174c0e","reportUrl":"../2/index.html#testresult/391488c3c9174c0e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/8445ede51857ce7b42f9ef7a26ce4c7d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc8886cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321936248,"stop":1717321936252,"duration":4}},{"uid":"9f2afe745feeeb40","reportUrl":"../1/index.html#testresult/9f2afe745feeeb40","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/8445ede51857ce7b42f9ef7a26ce4c7d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc8886cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321936248,"stop":1717321936252,"duration":4}},{"uid":"4730a823ca004c5f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/8445ede51857ce7b42f9ef7a26ce4c7d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc8886cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321936248,"stop":1717321936252,"duration":4}},{"uid":"98b2c22fb57453be","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/8445ede51857ce7b42f9ef7a26ce4c7d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc8886cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321936248,"stop":1717321936252,"duration":4}}]},"2a4fa39deef3548db49865f1d4f2b2a9":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"fe798276f65752e0","status":"passed","time":{"start":1716908357793,"stop":1716908367209,"duration":9416}}]},"2236edc766d60472faf614e72480776f":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"71cea6870e93396a","status":"passed","time":{"start":1716908385633,"stop":1716908390628,"duration":4995}}]},"a8d2a29d32fadfe1f3642bbdcdabd108":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"c34092bbc05f5673","status":"passed","time":{"start":1716908374257,"stop":1716908379137,"duration":4880}}]},"1d9f20844db144de72679c54191bbd60":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":6,"unknown":0,"total":6},"items":[{"uid":"ed656254410ff5e3","status":"passed","time":{"start":1717321924360,"stop":1717321935569,"duration":11209}},{"uid":"eb0659c4a8d81d71","status":"passed","time":{"start":1717321924360,"stop":1717321935569,"duration":11209}},{"uid":"28dca8bad3aa8cf6","reportUrl":"../2/index.html#testresult/28dca8bad3aa8cf6","status":"passed","time":{"start":1717321924360,"stop":1717321935569,"duration":11209}},{"uid":"da9ee54eafe34ab5","reportUrl":"../1/index.html#testresult/da9ee54eafe34ab5","status":"passed","time":{"start":1717321924360,"stop":1717321935569,"duration":11209}},{"uid":"ca0ef6c5b84a4e2b","status":"passed","time":{"start":1717321924360,"stop":1717321935569,"duration":11209}},{"uid":"b412d167072c459f","status":"passed","time":{"start":1717321924360,"stop":1717321935569,"duration":11209}}]},"17a77e6ff649da5c2ef207a08a597ec4":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":0,"unknown":0,"total":6},"items":[{"uid":"50e1c821da1a00c4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/739efe7233a6ccad7c58c508eaddfec7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88a1e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935974,"stop":1717321935977,"duration":3}},{"uid":"a700866c628b63e4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/739efe7233a6ccad7c58c508eaddfec7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88a1e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935974,"stop":1717321935977,"duration":3}},{"uid":"518b1256c477a621","reportUrl":"../2/index.html#testresult/518b1256c477a621","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/739efe7233a6ccad7c58c508eaddfec7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88a1e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935974,"stop":1717321935977,"duration":3}},{"uid":"c3b07b552b07f1b2","reportUrl":"../1/index.html#testresult/c3b07b552b07f1b2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/739efe7233a6ccad7c58c508eaddfec7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88a1e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935974,"stop":1717321935977,"duration":3}},{"uid":"3c67382c5f0ebeb2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/739efe7233a6ccad7c58c508eaddfec7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88a1e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935974,"stop":1717321935977,"duration":3}},{"uid":"f2ec476e72f5a827","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39893): Max retries exceeded with url: /session/739efe7233a6ccad7c58c508eaddfec7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc88a1e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1717321935974,"stop":1717321935977,"duration":3}}]},"c652c805f9c5051e590e56c6f0a6de44":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"71c9fa86ba7d5890","status":"passed","time":{"start":1716908325505,"stop":1716908334160,"duration":8655}}]}}