version: '3.9'

services:

  cellenium:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared:/cellenium
    restart: on-failure
    ports:
      - ${CELLENIUM_PORT}
    healthcheck:
      test: ['CMD', 'python --version']
      interval: 10s
      retries: 10

  core:
    build:
      context: .
    depends_on:
      cellenium:
        condition: service_started
    volumes:
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}
    ports:
      - ${CORE_PORT}
    restart: on-failure

  tests:
      build:
        context: .
      depends_on:
        core:
          condition: service_healthy
        allure-server:
          condition: service_started
      ports:
        - ${TEST_PORT}
      environment:
        - DEBUG=true
      command: >
        bash -c "pytest -n ${PARALLEL} && allure generate allure-results --clean -o allure-results && allure serve"
      volumes:
        - shared:/tests
      healthcheck:
        test: [ "CMD-SHELL", "curl -f http://localhost:${PORT} || exit 1" ]
        interval: 30s
        timeout: 10s
        retries: 5
      restart: on-failure

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"
    healthcheck:
      test: ["CMD", "allure --version"]
      interval: 10s
      retries: 6
    restart: on-failure

volumes:
  shared:
